### ISSUE TITLE
First action

### ISSUE THREAD

**Issue by mediaformat** [uuttff8/Remmel#20]
v1.1.13 (49)
The instances screen displays an _Add_ button along with links to _terms & conditions_
When accessing the _Add_ screen the text at the top displays _Create Instance_ (This is ambiguous, are we really trying to create an instance from this app?)

Attempting to login to my account at an existing instance.
I have tried adding the following combinations: 
- lemmy.ml
- https://lemmy.ml

But the _Add_ button remains disabled.

**Comment by uuttff8** [comment]
well, it’s really ambiguous. By creating instances i mean adding your custom instance. And yea, text will be changed. 

The Add button maybe disabled because you are trying to enter an instance with older (or unsupported yet) version of API. Remmel 1.1.13 are supporting API version <0.10.0, so it’s is disabled. I will add a warning about it. 

The very new version of lemmy api is a 0.11.0. Remmel  v1.3.0 that supports 0.11.0 are currently under review in the App Store, probably will be available soon

**Comment by mediaformat** [comment]
I think this issue can be closed!

By the way, the App Store text still has a big warning at the top.
"WARNING: Support only for API v2"
